{% set version = "1.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-igraph
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/igraph_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/igraph/igraph_{{ version }}.tar.gz
  sha256: d80778ff0fd0ee00a348c5d63b3b398b7467a1af49d85dc57fbee0a900fd7306

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}sed                   # [win]
    - {{ posix }}grep                  # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake              # [not win]
    - {{ posix }}automake-wrapper      # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - r-matrix                         # [build_platform != target_platform]
    - r-magrittr                       # [build_platform != target_platform]
    - r-pkgconfig >=2.0.0              # [build_platform != target_platform]
    - r-cpp11 >=0.2.0                  # [build_platform != target_platform]
    - r-rlang                          # [build_platform != target_platform]
  host:
    - r-base
    - libblas
    - liblapack
    - glpk >=4.57           # [not win]
    - gmp                   # [not win]
    - libxml2
    - r-matrix
    - r-magrittr
    - r-pkgconfig >=2.0.0
    - r-cpp11 >=0.2.0
    - r-rlang
  run:
    - r-base
    - glpk >=4.57           # [not win]
    - gmp                   # [not win]
    - libxml2
    - {{ native }}gcc-libs  # [win]
    - r-matrix
    - r-magrittr
    - r-pkgconfig >=2.0.0
    - r-cpp11 >=0.2.0
    - r-rlang

test:
  commands:
    - $R -e "library('igraph')"           # [not win]
    - "\"%R%\" -e \"library('igraph')\""  # [win]

about:
  home: https://r.igraph.org/
  dev_url: https://github.com/igraph/rigraph
  license: GPL-2.0-or-later
  summary: Routines for simple graphs and network analysis. It can handle large graphs very well and provides functions for generating random and regular graphs, graph visualization, centrality methods and much more.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
