{% set version = '1.2.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-igraph
  version: {{ version|replace("-", "_") }}

source:
  fn: igraph_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/igraph_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/igraph/igraph_{{ version }}.tar.gz
  sha256: 55341848f85a436c32d60f59a4db485238d535f2e8afe0d5a360804fc33299c1

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-matrix
    - r-magrittr
    - r-pkgconfig
    - {{native}}gmp >=5.0.1,<7
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-magrittr
    - r-pkgconfig
    - {{native}}gmp >=5.0.1,<7

test:
  commands:
    - $R -e "library('igraph')"           # [not win]
    - "\"%R%\" -e \"library('igraph')\""  # [win]

about:
  home: http://igraph.org
  license: GPL (>= 2)
  summary: Routines for simple graphs and network analysis. It can handle large graphs very well
    and provides functions for generating random and regular graphs, graph visualization,
    centrality methods and much more.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
