{% set version = "1.2.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-igraph
  version: {{ version|replace("-", "_") }}

source:
  fn: igraph_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/igraph_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/igraph/igraph_{{ version }}.tar.gz
  sha256: 9da2dadf9c1ed495413b32464c6a32fae9d33636822754043e708d8dd6a9efad

build:
  merge_build_host: True  # [win]
  number: 0
  # compilation errors on windows
  skip: true  # [win]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-matrix
    - r-nmf
    - r-irlba
    - r-magrittr
    - r-pkgconfig
    - {{native}}gmp >=5.0.1,<7

  run:
    - r-base
    - r-matrix
    - r-nmf
    - r-irlba
    - r-magrittr
    - r-pkgconfig
    - {{native}}gmp >=5.0.1,<7

test:
  commands:
    - $R -e "library('igraph')"  # [not win]
    - "\"%R%\" -e \"library('igraph')\""  # [win]

about:
  home: http://igraph.org
  license: GPL (>= 2)
  summary: Routines for simple graphs and network analysis. It can handle large graphs very well
    and provides functions for generating random and regular graphs, graph visualization,
    centrality methods and much more.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
