{% set version = "2.0.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-igraph
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/igraph_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/igraph/igraph_{{ version }}.tar.gz
  sha256: 8e8a172d4567219474562cfb1085496be3ab356483c4e88011aca1fc3b2d8f76
  patches:
    - patches/0001-conditional-rgl-tests.patch

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ stdlib('c') }}
    - {{ posix }}filesystem            # [win]
    - {{ posix }}sed                   # [win]
    - {{ posix }}grep                  # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake              # [not win]
    - {{ posix }}automake-wrapper      # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - r-cli                            # [build_platform != target_platform]
    - r-cpp11 >=0.4.7                  # [build_platform != target_platform]
    - r-lifecycle                      # [build_platform != target_platform]
    - r-magrittr                       # [build_platform != target_platform]
    - r-matrix                         # [build_platform != target_platform]
    - r-pkgconfig >=2.0.0              # [build_platform != target_platform]
    - r-rlang                          # [build_platform != target_platform]
    - r-vctrs                          # [build_platform != target_platform]
  host:
    - r-base
    - libblas
    - liblapack
    - glpk                             # [not win]
    - gmp                              # [not win]
    - libxml2
    - r-cli
    - r-cpp11 >=0.4.7
    - r-lifecycle
    - r-magrittr
    - r-matrix
    - r-pkgconfig >=2.0.0
    - r-rlang
    - r-vctrs
  run:
    - r-base
    - {{ native }}gcc-libs             # [win]
    - r-cli
    - r-cpp11 >=0.4.7
    - r-lifecycle
    - r-magrittr
    - r-matrix
    - r-pkgconfig >=2.0.0
    - r-rlang
    - r-vctrs

test:
  requires:
    - r-testthat
    - r-rgl       # [not ppc64le]
    - r-vdiffr
    - r-withr
  source_files:
    - tests/
  commands:
    - $R -e "library('igraph')"                                              # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"  # [not win]
    - "\"%R%\" -e \"library('igraph')\""                                              # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://r.igraph.org/
  dev_url: https://github.com/igraph/rigraph
  license: GPL-2.0-or-later
  summary: Routines for simple graphs and network analysis. It can handle large graphs very well and provides functions for generating random and regular graphs, graph visualization, centrality methods and much more.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
